 
version: '3'

services:
  mon_prometheus:
    image: prom/prometheus:latest
    container_name: mon_prometheus
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://10.10.10.10:9090'
      - '--storage.tsdb.retention.time=1y'
    ports:
      - 9090:9090
    networks:
      - monitoring

  mon_grafana:
    image: grafana/grafana:latest
    container_name: mon_grafana
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    user: "1000"
    depends_on:
      - mon_prometheus
    networks:
      - monitoring


networks:
  monitoring:

volumes:
  grafana:
  prometheus:
